services:
  redis:
    image: redis:7-alpine
    container_name: swush-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - swush-redis:/data:rw

  app:
    image: iconical/swush:latest
    container_name: swush-app
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      JOB_RUNNER_ROLE: api
      RUN_DB_MIGRATIONS: "true"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      redis:
        condition: service_healthy

    ports:
      - "3419:3000"
    volumes:
      # Can be removed if you don't want to persist uploads outside the container or using S3 for uploads
      - swush-uploads:/data/uploads:rw

  worker:
    image: iconical/swush:latest
    container_name: swush-worker
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      JOB_RUNNER_ROLE: worker
      RUN_DB_MIGRATIONS: "false"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - swush-uploads:/data/uploads:rw

volumes:
  swush-uploads:
  swush-redis:
